services:
  frontend:
    build:
      context: ./dashboard-raspberry-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ms-video-streaming
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    build:
      context: ./DashboardRaspberryBackend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "3001:80"
    depends_on:
      - ms-get-temperature-and-humidify
      - ms-get-soil-moisture
      - rabbitmq
    networks:
      app-network:
        aliases:
          - backend

  ms-get-temperature-and-humidify:
    build:
      context: ./MSGetTemperatureAndHumidify
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    networks:
      app-network:
        aliases:
          - ms-get-temperature-and-humidify

  ms-get-soil-moisture:
    build:
      context: ./MSGetSoilMoisture
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    networks:
      app-network:
        aliases:
          - ms-get-soil-moisture
  
  ms-video-streaming:
    build:
      context: ./MSVideoStreaming
    ports:
      - "5003:5003"
    # devices:
      # - "/dev/video0:/dev/video0"
    networks:
      app-network:
        aliases:
          - ms-video-streaming
  
  ms-pump-control:
    build:
      context: ./MSPumpControl
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq
    networks:
      app-network:
        aliases:
          - ms-pump-control

  ms-microcontroller-manager:
    build:
      context: ./MSMicrocontrollerManager
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
    networks:
      app-network:
        aliases:
          - microcontroller_manager #todo: fix needed

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
      - "1883:1883"    # MQTT port
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/logs:/var/log/rabbitmq
    networks:
      app-network:
        aliases:
          - rabbitmq

networks:
  app-network:
    driver: bridge