services:
  frontend:
    build:
      context: ./dashboard-raspberry-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    build:
      context: ./DashboardRaspberryBackend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "3001:80"
    depends_on:
      - ms-get-temperature-and-humidify
      - ms-get-soil-moisture
    networks:
      app-network:
        aliases:
          - backend

  ms-get-temperature-and-humidify:
    build:
      context: ./MSGetTemperatureAndHumidify
    ports:
      - "5000:5000"
    networks:
      app-network:
        aliases:
          - ms-get-temperature-and-humidify

  ms-get-soil-moisture:
    build:
      context: ./MSGetSoilMoisture
    ports:
      - "5001:5001"
    networks:
      app-network:
        aliases:
          - ms-get-soil-moisture

networks:
  app-network:
    driver: bridge