services:
  frontend:
    build:
      context: ./dashboard-raspberry-react
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./DashboardRaspberryBackend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "3001:80"
    depends_on:
      - ms-get-temperature-and-humidify

  ms-get-temperature-and-humidify:
    build:
      context: ./MSGetTemperatureAndHumidify
    ports:
      - "5000:5000"