version: '3.8'

services:
  frontend:
    build:
      context: ./dashboard-raspberry-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./DashboardRaspberryBackend
    ports:
      - "3001:3001"
    depends_on:
      - MSGetTemperatureAndHumidify

  MSGetTemperatureAndHumidify:
    build:
      context: ./MSGetTemperatureAndHumidify
    ports:
      - "3003:3003"